### ISSUE TITLE
Two edtions are ok. THANKS

### ISSUE THREAD

**Issue by alice-cool** [arashamini/PyTorch-RNNs#1]
In GRUCELL

 h_tilde = torch.tanh(output_i + (torch.mm((r * h_t_minus_1), self.weight_hh[:, idx:]) + self.bias_hh[idx:]))
        h = (1 - z) * **h_t_minus_1** + z * **h_tilde**
        return h`

 I found the function in Pytorch GRUCELL， I found the pytorch realise is different from the original paper.

Thanks

**Comment by arashamini** [comment]
I followed the equation 5 from [paper](https://arxiv.org/pdf/1412.3555.pdf), but both versions are correct.
